import {
  ScanBarcode,
  Settings,
  Users,
  ShoppingCartIcon,
  Package,
  PlusCircle,
  ShoppingCart,
  Wallet,
  LayoutDashboard,
  FileText,
  CreditCard,
  Keyboard,
  PartyPopper,
  Sparkles,
  Building2,
  Receipt,
} from "lucide-react";

export interface TutorialStep {
  id: number;
  titleKey: string;
  descriptionKey: string;
  icon: React.ComponentType<{ className?: string }>;
  route: string;
  /** CSS selector for the element to highlight (null = centered dialog) */
  targetSelector: string | null;
  /** Position of the floating dialog relative to target */
  position: "right" | "bottom" | "center";
  /** Whether this step requires navigating to a different route */
  navigates: boolean;
  /** Module name for the "go to X" waiting state */
  moduleKey: string;
  /**
   * Imagen ilustrativa, encima de la descripción. Opcional a propósito: solo
   * algunos pasos la tienen y los demás no se tocan.
   */
  image?: { src: string; alt: string };
}

export const tutorialSteps: TutorialStep[] = [
  {
    id: 1,
    titleKey: "tutorial.steps.scanner.title",
    descriptionKey: "tutorial.steps.scanner.description",
    icon: ScanBarcode,
    route: "/dashboard",
    targetSelector: null,
    position: "center",
    navigates: false,
    moduleKey: "",
    image: {
      src: "/lector-de-barras.png",
      alt: "Lector de código de barras escaneando la etiqueta de un producto",
    },
  },
  {
    id: 2,
    titleKey: "tutorial.steps.welcome.title",
    descriptionKey: "tutorial.steps.welcome.description",
    icon: Sparkles,
    route: "/dashboard",
    targetSelector: null,
    position: "center",
    navigates: false,
    moduleKey: "",
  },
  {
    id: 3,
    titleKey: "tutorial.steps.business.title",
    descriptionKey: "tutorial.steps.business.description",
    icon: Building2,
    route: "/settings",
    targetSelector: 'a[href*="/settings"]',
    position: "right",
    navigates: true,
    moduleKey: "layout.settings",
  },
  {
    id: 4,
    titleKey: "tutorial.steps.users.title",
    descriptionKey: "tutorial.steps.users.description",
    icon: Users,
    route: "/users",
    targetSelector: 'a[href*="/users"]',
    position: "right",
    navigates: true,
    moduleKey: "layout.users",
  },
  {
    id: 5,
    titleKey: "tutorial.steps.suppliers.title",
    descriptionKey: "tutorial.steps.suppliers.description",
    icon: ShoppingCartIcon,
    route: "/purchases",
    targetSelector: 'a[href*="/purchases"]',
    position: "right",
    navigates: true,
    moduleKey: "layout.purchases",
  },
  {
    id: 6,
    titleKey: "tutorial.steps.products.title",
    descriptionKey: "tutorial.steps.products.description",
    icon: Package,
    route: "/products",
    targetSelector: 'a[href*="/products"]',
    position: "right",
    navigates: true,
    moduleKey: "layout.products",
  },
  {
    id: 7,
    titleKey: "tutorial.steps.createProduct.title",
    descriptionKey: "tutorial.steps.createProduct.description",
    icon: PlusCircle,
    route: "/products",
    targetSelector: "#tutorial-add-product-btn",
    position: "bottom",
    navigates: false,
    moduleKey: "",
  },
  {
    id: 8,
    titleKey: "tutorial.steps.openCash.title",
    descriptionKey: "tutorial.steps.openCash.description",
    icon: ShoppingCart,
    route: "/finances",
    targetSelector: "#tutorial-open-cash-btn",
    position: "bottom",
    navigates: true,
    moduleKey: "layout.finances",
  },
  {
    id: 9,
    titleKey: "tutorial.steps.firstSale.title",
    descriptionKey: "tutorial.steps.firstSale.description",
    icon: Receipt,
    route: "/pos",
    targetSelector: null,
    position: "center",
    navigates: true,
    moduleKey: "layout.pos",
  },
  {
    id: 10,
    titleKey: "tutorial.steps.closeCash.title",
    descriptionKey: "tutorial.steps.closeCash.description",
    icon: Wallet,
    route: "/finances",
    targetSelector: "#tutorial-close-cash-btn",
    position: "bottom",
    navigates: true,
    moduleKey: "layout.finances",
  },
  {
    id: 11,
    titleKey: "tutorial.steps.reports.title",
    descriptionKey: "tutorial.steps.reports.description",
    icon: LayoutDashboard,
    route: "/dashboard",
    targetSelector: 'a[href*="/dashboard"]',
    position: "right",
    navigates: true,
    moduleKey: "layout.dashboard",
  },
  {
    id: 12,
    titleKey: "tutorial.steps.activity.title",
    descriptionKey: "tutorial.steps.activity.description",
    icon: FileText,
    route: "/activity",
    targetSelector: 'a[href*="/activity"]',
    position: "right",
    navigates: true,
    moduleKey: "common.activityLog",
  },
  {
    id: 13,
    titleKey: "tutorial.steps.billing.title",
    descriptionKey: "tutorial.steps.billing.description",
    icon: CreditCard,
    route: "/billing",
    targetSelector: 'a[href*="/billing"]',
    position: "right",
    navigates: true,
    moduleKey: "layout.billing",
  },
  {
    id: 14,
    titleKey: "tutorial.steps.advancedSettings.title",
    descriptionKey: "tutorial.steps.advancedSettings.description",
    icon: Settings,
    route: "/settings",
    targetSelector: "#settings-tab-modules",
    position: "bottom",
    navigates: true,
    moduleKey: "layout.settings",
  },
  {
    id: 15,
    titleKey: "tutorial.steps.shortcuts.title",
    descriptionKey: "tutorial.steps.shortcuts.description",
    icon: Keyboard,
    route: "/dashboard",
    targetSelector: null,
    position: "center",
    navigates: false,
    moduleKey: "",
  },
  {
    id: 16,
    titleKey: "tutorial.steps.complete.title",
    descriptionKey: "tutorial.steps.complete.description",
    icon: PartyPopper,
    route: "/dashboard",
    targetSelector: null,
    position: "center",
    navigates: false,
    moduleKey: "",
  },
];
