import {
  Settings,
  Users,
  ShoppingCartIcon,
  Package,
  PlusCircle,
  ShoppingCart,
  Wallet,
  LayoutDashboard,
  FileText,
  CreditCard,
  Keyboard,
  PartyPopper,
  Sparkles,
  Building2,
  Receipt,
} from "lucide-react";

export interface TutorialStep {
  id: number;
  titleKey: string;
  descriptionKey: string;
  icon: React.ComponentType<{ className?: string }>;
  route: string;
  /** CSS selector for the element to spotlight (null = centered dialog) */
  targetSelector: string | null;
  /** Position of the floating dialog relative to target */
  position: "right" | "bottom" | "center";
  /** Whether this step requires navigating to a different route */
  navigates: boolean;
}

export const tutorialSteps: TutorialStep[] = [
  {
    id: 1,
    titleKey: "tutorial.steps.welcome.title",
    descriptionKey: "tutorial.steps.welcome.description",
    icon: Sparkles,
    route: "/dashboard",
    targetSelector: null,
    position: "center",
    navigates: false,
  },
  {
    id: 2,
    titleKey: "tutorial.steps.business.title",
    descriptionKey: "tutorial.steps.business.description",
    icon: Building2,
    route: "/settings",
    targetSelector: 'a[href*="/settings"]',
    position: "right",
    navigates: true,
  },
  {
    id: 3,
    titleKey: "tutorial.steps.users.title",
    descriptionKey: "tutorial.steps.users.description",
    icon: Users,
    route: "/users",
    targetSelector: 'a[href*="/users"]',
    position: "right",
    navigates: true,
  },
  {
    id: 4,
    titleKey: "tutorial.steps.suppliers.title",
    descriptionKey: "tutorial.steps.suppliers.description",
    icon: ShoppingCartIcon,
    route: "/purchases",
    targetSelector: 'a[href*="/purchases"]',
    position: "right",
    navigates: true,
  },
  {
    id: 5,
    titleKey: "tutorial.steps.products.title",
    descriptionKey: "tutorial.steps.products.description",
    icon: Package,
    route: "/products",
    targetSelector: 'a[href*="/products"]',
    position: "right",
    navigates: true,
  },
  {
    id: 6,
    titleKey: "tutorial.steps.createProduct.title",
    descriptionKey: "tutorial.steps.createProduct.description",
    icon: PlusCircle,
    route: "/products",
    targetSelector: "button",
    position: "bottom",
    navigates: false,
  },
  {
    id: 7,
    titleKey: "tutorial.steps.openCash.title",
    descriptionKey: "tutorial.steps.openCash.description",
    icon: ShoppingCart,
    route: "/pos",
    targetSelector: 'a[href*="/pos"]',
    position: "right",
    navigates: true,
  },
  {
    id: 8,
    titleKey: "tutorial.steps.firstSale.title",
    descriptionKey: "tutorial.steps.firstSale.description",
    icon: Receipt,
    route: "/pos",
    targetSelector: null,
    position: "center",
    navigates: false,
  },
  {
    id: 9,
    titleKey: "tutorial.steps.closeCash.title",
    descriptionKey: "tutorial.steps.closeCash.description",
    icon: Wallet,
    route: "/finances",
    targetSelector: 'a[href*="/finances"]',
    position: "right",
    navigates: true,
  },
  {
    id: 10,
    titleKey: "tutorial.steps.reports.title",
    descriptionKey: "tutorial.steps.reports.description",
    icon: LayoutDashboard,
    route: "/dashboard",
    targetSelector: 'a[href*="/dashboard"]',
    position: "right",
    navigates: true,
  },
  {
    id: 11,
    titleKey: "tutorial.steps.activity.title",
    descriptionKey: "tutorial.steps.activity.description",
    icon: FileText,
    route: "/activity",
    targetSelector: 'a[href*="/activity"]',
    position: "right",
    navigates: true,
  },
  {
    id: 12,
    titleKey: "tutorial.steps.billing.title",
    descriptionKey: "tutorial.steps.billing.description",
    icon: CreditCard,
    route: "/billing",
    targetSelector: 'a[href*="/billing"]',
    position: "right",
    navigates: true,
  },
  {
    id: 13,
    titleKey: "tutorial.steps.advancedSettings.title",
    descriptionKey: "tutorial.steps.advancedSettings.description",
    icon: Settings,
    route: "/settings",
    targetSelector: 'a[href*="/settings"]',
    position: "right",
    navigates: true,
  },
  {
    id: 14,
    titleKey: "tutorial.steps.shortcuts.title",
    descriptionKey: "tutorial.steps.shortcuts.description",
    icon: Keyboard,
    route: "/dashboard",
    targetSelector: null,
    position: "center",
    navigates: false,
  },
  {
    id: 15,
    titleKey: "tutorial.steps.complete.title",
    descriptionKey: "tutorial.steps.complete.description",
    icon: PartyPopper,
    route: "/dashboard",
    targetSelector: null,
    position: "center",
    navigates: false,
  },
];
