-- SYMVORA SaaS - Initial Schema Migration
-- Multi-Tenant ERP with Row-Level Security

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================
-- ENUMS
-- =============================================

CREATE TYPE public.app_role AS ENUM ('SUPER_ADMIN', 'ORG_ADMIN', 'CAJERO');
CREATE TYPE public.unidad_medida AS ENUM ('PIEZA', 'KG', 'GRAMO', 'LITRO', 'SERVICIO');
CREATE TYPE public.metodo_pago AS ENUM ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'CREDITO');
CREATE TYPE public.estado_venta AS ENUM ('COMPLETADA', 'CANCELADA', 'PENDIENTE');
CREATE TYPE public.estado_compra AS ENUM ('PENDIENTE', 'RECIBIDA', 'CANCELADA');
CREATE TYPE public.estado_caja AS ENUM ('ABIERTA', 'CERRADA');
CREATE TYPE public.tipo_movimiento AS ENUM ('ENTRADA', 'SALIDA');

-- =============================================
-- TABLES
-- =============================================

-- Tenants table
CREATE TABLE public.tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre_comercial TEXT NOT NULL,
  subdominio TEXT UNIQUE NOT NULL,
  giro_comercial TEXT NOT NULL,
  logo_url TEXT,
  color_primario TEXT,
  direccion TEXT,
  telefono TEXT,
  email TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Tenant settings (JSONB for feature flags)
CREATE TABLE public.tenant_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  configuracion_json JSONB NOT NULL DEFAULT '{}',
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(tenant_id)
);

-- User roles
CREATE TABLE public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role app_role NOT NULL,
  UNIQUE(user_id, role)
);

-- Tenant memberships
CREATE TABLE public.tenant_memberships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role app_role NOT NULL DEFAULT 'CAJERO',
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(tenant_id, user_id)
);

-- Products
CREATE TABLE public.productos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  codigo_barras TEXT,
  sku TEXT,
  nombre TEXT NOT NULL,
  descripcion TEXT,
  unidad_medida unidad_medida NOT NULL DEFAULT 'PIEZA',
  precio_venta DECIMAL(10,2) NOT NULL DEFAULT 0,
  costo_compra DECIMAL(10,2) NOT NULL DEFAULT 0,
  stock_actual DECIMAL(10,3) NOT NULL DEFAULT 0,
  stock_minimo DECIMAL(10,3) NOT NULL DEFAULT 0,
  es_servicio BOOLEAN NOT NULL DEFAULT FALSE,
  permite_variantes BOOLEAN NOT NULL DEFAULT FALSE,
  permite_lotes BOOLEAN NOT NULL DEFAULT FALSE,
  categoria TEXT,
  proveedor_id UUID,
  imagen_url TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Customers
CREATE TABLE public.clientes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  email TEXT,
  telefono TEXT,
  direccion TEXT,
  limite_credito DECIMAL(10,2) NOT NULL DEFAULT 0,
  saldo_pendiente DECIMAL(10,2) NOT NULL DEFAULT 0,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Suppliers
CREATE TABLE public.proveedores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  contact_name TEXT,
  email TEXT,
  telefono TEXT,
  direccion TEXT,
  tiempo_surtido TEXT,
  condiciones_comerciales TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Sales
CREATE TABLE public.ventas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  usuario_id UUID NOT NULL REFERENCES auth.users(id),
  cliente_id UUID REFERENCES public.clientes(id),
  total DECIMAL(10,2) NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  impuesto DECIMAL(10,2) NOT NULL DEFAULT 0,
  descuento DECIMAL(10,2) NOT NULL DEFAULT 0,
  metodo_pago metodo_pago NOT NULL,
  estado estado_venta NOT NULL DEFAULT 'COMPLETADA',
  notas TEXT,
  fecha_venta TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Sale details
CREATE TABLE public.detalle_ventas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  venta_id UUID NOT NULL REFERENCES public.ventas(id) ON DELETE CASCADE,
  producto_id UUID NOT NULL REFERENCES public.productos(id),
  cantidad DECIMAL(10,3) NOT NULL,
  precio_unitario DECIMAL(10,2) NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  descuento DECIMAL(10,2) NOT NULL DEFAULT 0
);

-- Purchases
CREATE TABLE public.compras (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  proveedor_id UUID NOT NULL REFERENCES public.proveedores(id),
  usuario_id UUID NOT NULL REFERENCES auth.users(id),
  numero_factura TEXT,
  total DECIMAL(10,2) NOT NULL,
  estado estado_compra NOT NULL DEFAULT 'PENDIENTE',
  fecha_compra TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_recepcion TIMESTAMPTZ,
  notas TEXT
);

-- Purchase details
CREATE TABLE public.detalle_compras (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  compra_id UUID NOT NULL REFERENCES public.compras(id) ON DELETE CASCADE,
  producto_id UUID NOT NULL REFERENCES public.productos(id),
  cantidad DECIMAL(10,3) NOT NULL,
  costo_unitario DECIMAL(10,2) NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL
);

-- Cash registers
CREATE TABLE public.cajas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  usuario_id UUID NOT NULL REFERENCES auth.users(id),
  fondo_inicial DECIMAL(10,2) NOT NULL,
  total_ventas DECIMAL(10,2) NOT NULL DEFAULT 0,
  total_entradas DECIMAL(10,2) NOT NULL DEFAULT 0,
  total_salidas DECIMAL(10,2) NOT NULL DEFAULT 0,
  saldo_esperado DECIMAL(10,2) NOT NULL DEFAULT 0,
  saldo_real DECIMAL(10,2) NOT NULL DEFAULT 0,
  diferencia DECIMAL(10,2) NOT NULL DEFAULT 0,
  estado estado_caja NOT NULL DEFAULT 'ABIERTA',
  fecha_apertura TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_cierre TIMESTAMPTZ,
  notas_apertura TEXT,
  notas_cierre TEXT
);

-- Cash register movements
CREATE TABLE public.movimientos_caja (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  caja_id UUID NOT NULL REFERENCES public.cajas(id) ON DELETE CASCADE,
  tipo tipo_movimiento NOT NULL,
  monto DECIMAL(10,2) NOT NULL,
  descripcion TEXT NOT NULL,
  fecha TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================
-- INDEXES
-- =============================================

-- Tenant-scoped indexes (tenant_id as leading column)
CREATE INDEX idx_tenant_settings_tenant ON public.tenant_settings(tenant_id);
CREATE INDEX idx_tenant_memberships_tenant ON public.tenant_memberships(tenant_id);
CREATE INDEX idx_tenant_memberships_user ON public.tenant_memberships(user_id);
CREATE INDEX idx_user_roles_user ON public.user_roles(user_id);
CREATE INDEX idx_productos_tenant ON public.productos(tenant_id);
CREATE INDEX idx_productos_codigo_barras ON public.productos(codigo_barras);
CREATE INDEX idx_clientes_tenant ON public.clientes(tenant_id);
CREATE INDEX idx_proveedores_tenant ON public.proveedores(tenant_id);
CREATE INDEX idx_ventas_tenant ON public.ventas(tenant_id);
CREATE INDEX idx_ventas_usuario ON public.ventas(usuario_id);
CREATE INDEX idx_ventas_fecha ON public.ventas(fecha_venta);
CREATE INDEX idx_detalle_ventas_venta ON public.detalle_ventas(venta_id);
CREATE INDEX idx_detalle_ventas_producto ON public.detalle_ventas(producto_id);
CREATE INDEX idx_compras_tenant ON public.compras(tenant_id);
CREATE INDEX idx_compras_proveedor ON public.compras(proveedor_id);
CREATE INDEX idx_detalle_compras_compra ON public.detalle_compras(compra_id);
CREATE INDEX idx_cajas_tenant ON public.cajas(tenant_id);
CREATE INDEX idx_cajas_usuario ON public.cajas(usuario_id);
CREATE INDEX idx_cajas_estado ON public.cajas(estado);
CREATE INDEX idx_movimientos_caja_caja ON public.movimientos_caja(caja_id);

-- =============================================
-- FUNCTIONS
-- =============================================

-- Function to get user's tenant IDs
CREATE OR REPLACE FUNCTION public.user_tenant_ids()
RETURNS SETOF UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT tenant_id
  FROM public.tenant_memberships
  WHERE user_id = auth.uid()
$$;

-- Grant execute to authenticated users
REVOKE ALL ON FUNCTION public.user_tenant_ids() FROM public;
GRANT EXECUTE ON FUNCTION public.user_tenant_ids() TO authenticated;

-- Function to check user permissions
CREATE OR REPLACE FUNCTION public.authorize(
  requested_permission TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  user_role public.app_role;
  bind_permissions INT;
BEGIN
  -- Read role from JWT
  SELECT (auth.jwt() ->> 'user_role')::public.app_role INTO user_role;

  IF user_role IS NULL THEN
    RETURN FALSE;
  END IF;

  -- Check if role has the permission
  SELECT COUNT(*)
  INTO bind_permissions
  FROM public.role_permissions
  WHERE role_permissions.permission = requested_permission
    AND role_permissions.role = user_role;

  RETURN bind_permissions > 0;
END;
$$;

-- =============================================
-- RLS POLICIES
-- =============================================

-- Enable RLS on all tables
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_compras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cajas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimientos_caja ENABLE ROW LEVEL SECURITY;

-- Tenant isolation policies (JWT claims pattern)
CREATE POLICY "tenant_isolation" ON public.tenants
FOR ALL TO authenticated
USING (
  id IN (SELECT public.user_tenant_ids())
);

CREATE POLICY "tenant_settings_isolation" ON public.tenant_settings
FOR ALL TO authenticated
USING (
  tenant_id IN (SELECT public.user_tenant_ids())
);

CREATE POLICY "tenant_memberships_isolation" ON public.tenant_memberships
FOR ALL TO authenticated
USING (
  tenant_id IN (SELECT public.user_tenant_ids())
);

CREATE POLICY "productos_isolation" ON public.productos
FOR ALL TO authenticated
USING (
  tenant_id IN (SELECT public.user_tenant_ids())
);

CREATE POLICY "clientes_isolation" ON public.clientes
FOR ALL TO authenticated
USING (
  tenant_id IN (SELECT public.user_tenant_ids())
);

CREATE POLICY "proveedores_isolation" ON public.proveedores
FOR ALL TO authenticated
USING (
  tenant_id IN (SELECT public.user_tenant_ids())
);

CREATE POLICY "ventas_isolation" ON public.ventas
FOR ALL TO authenticated
USING (
  tenant_id IN (SELECT public.user_tenant_ids())
);

CREATE POLICY "detalle_ventas_isolation" ON public.detalle_ventas
FOR ALL TO authenticated
USING (
  venta_id IN (
    SELECT id FROM public.ventas
    WHERE tenant_id IN (SELECT public.user_tenant_ids())
  )
);

CREATE POLICY "compras_isolation" ON public.compras
FOR ALL TO authenticated
USING (
  tenant_id IN (SELECT public.user_tenant_ids())
);

CREATE POLICY "detalle_compras_isolation" ON public.detalle_compras
FOR ALL TO authenticated
USING (
  compra_id IN (
    SELECT id FROM public.compras
    WHERE tenant_id IN (SELECT public.user_tenant_ids())
  )
);

CREATE POLICY "cajas_isolation" ON public.cajas
FOR ALL TO authenticated
USING (
  tenant_id IN (SELECT public.user_tenant_ids())
);

CREATE POLICY "movimientos_caja_isolation" ON public.movimientos_caja
FOR ALL TO authenticated
USING (
  caja_id IN (
    SELECT id FROM public.cajas
    WHERE tenant_id IN (SELECT public.user_tenant_ids())
  )
);

-- User roles: users can read their own roles
CREATE POLICY "user_roles_own" ON public.user_roles
FOR SELECT TO authenticated
USING (
  user_id = auth.uid()
);

-- =============================================
-- CUSTOM ACCESS TOKEN HOOK
-- =============================================

-- This function is called by Supabase Auth to inject custom claims into the JWT
CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  claims JSONB;
  user_role public.app_role;
  tenant_id UUID;
BEGIN
  -- Fetch user's role and active tenant
  SELECT ur.role, tm.tenant_id
  INTO user_role, tenant_id
  FROM public.user_roles ur
  JOIN public.tenant_memberships tm ON tm.user_id = ur.user_id
  WHERE ur.user_id = (event->>'user_id')::UUID
  ORDER BY tm.creado_en DESC
  LIMIT 1;

  claims := event->'claims';

  IF user_role IS NOT NULL THEN
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role::text));
  ELSE
    claims := jsonb_set(claims, '{user_role}', 'null');
  END IF;

  IF tenant_id IS NOT NULL THEN
    claims := jsonb_set(claims, '{tenant_id}', to_jsonb(tenant_id::text));
  END IF;

  event := jsonb_set(event, '{claims}', claims);
  RETURN event;
END;
$$;

-- Grant permissions for the hook
GRANT USAGE ON SCHEMA public TO supabase_auth_admin;
GRANT EXECUTE ON FUNCTION public.custom_access_token_hook TO supabase_auth_admin;
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook FROM authenticated, anon, public;

GRANT ALL ON TABLE public.user_roles TO supabase_auth_admin;
REVOKE ALL ON TABLE public.user_roles FROM authenticated, anon, public;

CREATE POLICY "Allow auth admin to read user roles" ON public.user_roles
AS PERMISSIVE FOR SELECT TO supabase_auth_admin USING (true);

-- =============================================
-- ROLE PERMISSIONS SEED
-- =============================================

CREATE TABLE public.role_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role app_role NOT NULL,
  permission TEXT NOT NULL,
  UNIQUE(role, permission)
);

-- Seed permissions
INSERT INTO public.role_permissions (role, permission) VALUES
  -- SUPER_ADMIN permissions
  ('SUPER_ADMIN', 'org.delete'),
  ('SUPER_ADMIN', 'org.manage_members'),
  ('SUPER_ADMIN', 'org.manage_settings'),
  ('SUPER_ADMIN', 'sales.create'),
  ('SUPER_ADMIN', 'sales.void'),
  ('SUPER_ADMIN', 'sales.view_reports'),
  ('SUPER_ADMIN', 'inventory.manage'),
  ('SUPER_ADMIN', 'inventory.view'),
  ('SUPER_ADMIN', 'purchases.manage'),
  ('SUPER_ADMIN', 'finances.manage'),
  -- ORG_ADMIN permissions
  ('ORG_ADMIN', 'org.manage_members'),
  ('ORG_ADMIN', 'org.manage_settings'),
  ('ORG_ADMIN', 'sales.create'),
  ('ORG_ADMIN', 'sales.void'),
  ('ORG_ADMIN', 'sales.view_reports'),
  ('ORG_ADMIN', 'inventory.manage'),
  ('ORG_ADMIN', 'inventory.view'),
  ('ORG_ADMIN', 'purchases.manage'),
  ('ORG_ADMIN', 'finances.manage'),
  -- CAJERO permissions
  ('CAJERO', 'sales.create'),
  ('CAJERO', 'sales.view_reports'),
  ('CAJERO', 'inventory.view');
